"""empty message

Revision ID: 75024df2be0d
Revises: 
Create Date: 2022-02-11 12:03:51.303213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75024df2be0d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city', sa.String(length=60), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('rain_probability', sa.Integer(), nullable=False),
    sa.Column('rain_precipitation', sa.Integer(), nullable=False),
    sa.Column('max_temperature', sa.Integer(), nullable=False),
    sa.Column('min_temperature', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forecast')
    # ### end Alembic commands ###
